name: Update stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - .github/workflows/wakatime.yml

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: MelodyYuuka/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          COMMIT_EMAIL: "81250368+MelodyYuuka@users.noreply.github.com"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_TOTAL_CODE_TIME: "False"

  github-stats:
    name: Generate GitHub stats
    runs-on: ubuntu-latest
    needs: [update-readme]
    steps:
      - uses: actions/checkout@v6
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&count_private=true&show_icons=true&bg_color=15,f2f7fd,E0EAFC
          path: static/github-stats.svg
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: github-stats
          path: static/github-stats.svg

  wakatime-stats:
    name: Generate WakaTime stats
    runs-on: ubuntu-latest
    needs: [update-readme]
    steps:
      - uses: actions/checkout@v6
      - name: Generate wakatime card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: wakatime
          options: username=MelodyYuyuko&layout=compact&hide_border=true
          path: static/wakatime-stats.svg
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: wakatime-stats
          path: static/wakatime-stats.svg

  snake:
    name: Generate snake
    runs-on: ubuntu-latest
    needs: [update-readme]
    steps:
      - uses: actions/checkout@v6
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./static/github-contribution-grid-snake.gif
            ./static/github-contribution-grid-snake.svg
            ./static/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: static

  commit:
    name: Commit generated assets
    runs-on: ubuntu-latest
    needs: [github-stats, wakatime-stats, snake]
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v4
        with:
          name: github-stats
          path: static

      - uses: actions/download-artifact@v4
        with:
          name: wakatime-stats
          path: static

      - uses: actions/download-artifact@v4
        with:
          name: snake
          path: static

      - name: Commit
        run: |
          git config user.name "MelodyYuuka"
          git config user.email "81250368+MelodyYuuka@users.noreply.github.com"
          git add static
          git diff --cached --quiet || git commit -m ":bento: update github stats"
          git pull --rebase
          git push
